classDiagram
class Item {
  - codigo : String
  - titulo : String
}

class Exemplar {
  - tombo : String
}

Item "1" *-- "0..*" Exemplar : possui

class Usuario {
    - matricula : String
    - nome : String
}

class Emprestimo {
    -  algo : String
    - eOutraCoisa : String
}

Usuario "1" *-- "0..3" Emprestimo : quantidade

